#Vectors, Matrices, Arrays Part 1
 **Creating Vectors**

In [1]:
#Load Library
import numpy as np

In [2]:
#Create a row vector
row_vec=np.array([1,2,3])
row_vec

array([1, 2, 3])

In [3]:
#Create a Column vector
col_vec = np.array([[1],[2],[3]])
col_vec

array([[1],
       [2],
       [3]])

 **Creating Matrix**

There are two ways to create matrices using numpy


1.   Using 2-D Array
2.   Using Matrix data structure

Simplicity of 2-D Array over Matrix datastructure


1.   2-D Array is the standard data structure of Numpy
2.   Most of the Numpy operations returs array not matrix object


In [4]:
#Create matrix using 2-D array
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#Create matrix with matrix obje
mat_obj = np.mat([[1,2,3],[4,5,6],[7,8,9]])
mat_obj

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

 **Create Sparse Matrix**
Sparse matrix is a matrix which contains very few non-zero elements.

In [6]:
#Load libary specific to create sparse matrix
from scipy import sparse

In [7]:
#create sparse matrix
mat_sparse = np.array([[0,1,0,0,0],[1,0,0,1,0],[0,0,0,0,0],[0,0,3,0,5],[0,0,0,2,3]])
mat_sparse
sparse_all=sparse.csr_matrix(mat_sparse)

In [8]:
#show the allocation of the sparse matrix
print(sparse_all)

  (0, 1)	1
  (1, 0)	1
  (1, 3)	1
  (3, 2)	3
  (3, 4)	5
  (4, 3)	2
  (4, 4)	3


**Select element from an vector of matrix. (Slicing arrays)**

In [9]:
#Create a vector and matrix for slicing
vec_slicing = np.array([5,6,10,12,8,2])
vec_slicing

array([ 5,  6, 10, 12,  8,  2])

In [10]:
mat_slicing = np.array([[5,9,6],[2,3,4],[8,2,1]])
mat_slicing

array([[5, 9, 6],
       [2, 3, 4],
       [8, 2, 1]])

In [11]:
#select 2nd element of the vector
vec_slicing[3]

12

In [12]:
#select the element of 2nd row and 1st column of the matrix
mat_slicing[1,1]

3

In [13]:
#Select all element from the vector
vec_slicing[:]

array([ 5,  6, 10, 12,  8,  2])

In [14]:
#Select all the element after a certain element from a vector
vec_slicing[3:]

array([12,  8,  2])

In [15]:
#select the last element of the vector
vec_slicing[-1]

2

In [16]:
#select first 2 rows with all columns
mat_slicing[:2,:]

array([[5, 9, 6],
       [2, 3, 4]])

In [17]:
#Select all rows and the third column
mat_slicing[:,2:3]

array([[6],
       [4],
       [1]])

**Describing a matrix**

In [18]:
#print the number of rows and columns of the matrix
mat_slicing.shape

(3, 3)

In [19]:
#print the number of elements of the matrix
mat_slicing.size

9

In [20]:
#print the number of dimensions of the matrix
mat_slicing.ndim

2

**Create a matrix and add 100 to every element of the matrix**


1.   Using vectorize class
2.   Using Broadcasting method


In [21]:
#using vectorize class
# Create function that adds 100 to something
adding100 = lambda i: i + 100
# Create vectorized function
vectorized_adding100 = np.vectorize(adding100)
# Apply function to all elements in matrix
vectorized_adding100(mat_slicing)

array([[105, 109, 106],
       [102, 103, 104],
       [108, 102, 101]])

In [22]:
#using broadcasting
#Adding Scalar and One-Dimensional Array
a = np.array([2,4,3])
print(a)
b = 5
print(b)
c = a+b
print(c)

[2 4 3]
5
[7 9 8]


In [23]:
#Adding Scalar and Two-Dimensional Array
A = np.array([[1,7,1],[2,4,1]])
print(A)
B =2
print(B)
C = A+B
print(C)

[[1 7 1]
 [2 4 1]]
2
[[3 9 3]
 [4 6 3]]


In [24]:
#Adding One-Dimensional and Two-Dimensional Arrays
A = np.array([[1,7,1],[2,4,1]])
print(A)
B =np.array([[2,3,1]])
print(B)
C = A+B
print(C)

[[1 7 1]
 [2 4 1]]
[[2 3 1]]
[[ 3 10  2]
 [ 4  7  2]]


**Finding the minimum and maximum value from a matrix**

In [25]:
print(mat_slicing)

[[5 9 6]
 [2 3 4]
 [8 2 1]]


In [26]:
#Find maximum element of a matrix
np.max(mat_slicing)

9

In [27]:
#Find minimum element of a matrix
np.min(mat_slicing)

1

In [28]:
#Find the maximum and minimum element in each column of a matrix
print(np.max(mat_slicing, axis=0))
print(np.min(mat_slicing,axis=0))

[8 9 6]
[2 2 1]


In [29]:
#Find the maximum and minimum element in each row of a matrix
print(np.max(mat_slicing, axis=1))
print(np.min(mat_slicing, axis =1))

[9 4 8]
[5 2 1]


**Calculating the Average, Variance, and Standard**
**Deviation**

In [30]:
#Find out mean from a matrix
np.mean(mat_slicing)

4.444444444444445

In [31]:
#Find the mean value of each column of a matrix
np.mean(mat_slicing, axis=0)

array([5.        , 4.66666667, 3.66666667])

In [32]:
#Find out variance from a matrix
np.var(mat_slicing)

6.913580246913581

In [33]:
#Find out Standard deviation from a matrix
np.std(mat_slicing)

2.629368792488718